name: Binlist

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: OTP ${{ matrix.otp }} / Elixir ${{ matrix.elixir }}
    strategy:
      matrix:
        otp: ['19.x', '20.x', '21.x', '22.x']
        elixir: ['1.6', '1.7', '1.8', '1.9', '1.10']
        exclude:
          - otp: '20.x'
            elixir: '1.10'
          - otp: '19.x'
            elixir: '1.10'
          - otp: '19.x'
            elixir: '1.9'
          - otp: '19.x'
            elixir: '1.8'
          - otp: '22.x'
            elixir: '1.6'
          - otp: '21.x'
            elixir: '1.6'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - uses: actions/cache@v1
        with:
          path: deps
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles(format('{0}{1}', github.workspace, '/mix.lock')) }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-
      - name: Install Dependencies
        run: mix deps.get
      - name: Run Tests
        run: mix test
