name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    name: OTP ${{ matrix.otp }} / Elixir ${{ matrix.elixir }}
    strategy:
      matrix:
        otp: ['20.x', '21.x', '22.x', '23.x', '24.x']
        elixir: ['1.8', '1.9', '1.10', '1.11', '1.12']
        exclude:
          - otp: '20.x'
            elixir: '1.10'
          - otp: '20.x'
            elixir: '1.11'
          - otp: '20.x'
            elixir: '1.12'
          - otp: '21.x'
            elixir: '1.12'
          - otp: '23.x'
            elixir: '1.9'
          - otp: '23.x'
            elixir: '1.8'
          - otp: '24.x'
            elixir: '1.10'
          - otp: '24.x'
            elixir: '1.9'
          - otp: '24.x'
            elixir: '1.8'
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - name: Install Dependencies
        run: mix deps.get
      - name: Run Tests
        run: mix test
